const cases = {
    ORDER_AMOUNT_GREATER_OR_EQUAL_TO_LOWER_LIMIT: {
        name: 'ORDER_AMOUNT_GREATER_OR_EQUAL_TO_LOWER_LIMIT'
    },
    ORDER_AMOUNT_LESS_THAN_LOWER_LIMIT: {
        name: 'ORDER_AMOUNT_LESS_THAN_LOWER_LIMIT'
    },
    ORDER_AMOUNT_GREATER_OR_EQUAL_TO_UPPER_LIMIT: {
        name: 'ORDER_AMOUNT_GREATER_OR_EQUAL_TO_UPPER_LIMIT'
    },
    ORDER_AMOUNT_LESS_THAN_UPPER_LIMIT: {
        name: 'ORDER_AMOUNT_LESS_THAN_UPPER_LIMIT'
    },
    COLLECT_PAYMENT_METHOD: {
        name: 'COLLECT_PAYMENT_METHOD'
    },
}

export default cases